export interface BrewfileLinkDictionary {
    [key: string]: string;
}

export const brewfileLinkDictionary: BrewfileLinkDictionary = {
    "acarl005/formulas": "https://github.com/acarl005/ls-go",
    "getsentry/tools": "https://github.com/getsentry/sentry",
    "homebrew/bundle": "https://github.com/Homebrew/homebrew-bundle",
    "homebrew/cask-fonts": "https://github.com/Homebrew/homebrew-cask-fonts",
    "homebrew/services": "https://github.com/Homebrew/homebrew-services",
    "jandedobbeleer/oh-my-posh": "https://github.com/JanDeDobbeleer/oh-my-posh",
    "python@3.11": "https://www.python.org/downloads/release/python-3110/",
    "asciinema": "https://github.com/asciinema/asciinema",
    "autojump": "https://github.com/wting/autojump",
    "berkeley-db": "https://github.com/berkeleydb/libdb",
    "carthage": "https://github.com/Carthage/Carthage",
    "clang-format": "https://github.com/llvm-mirror/clang/tree/master/tools/clang-format",
    "create-dmg": "https://github.com/create-dmg/create-dmg",
    "dbus": "https://github.com/godbus/dbus",
    "ddgr": "",
    "docker": "",
    "docker-compose": "",
    "libssh2": "",
    "exa": "",
    "eza": "",
    "unbound": "",
    "ffmpeg": "",
    "figlet": "",
    "ncurses": "",
    "fish": "",
    "fzf": "",
    "gh": "",
    "jq": "",
    "kubernetes-cli": "",
    "libtensorflow": "",
    "lolcat": "",
    "multitime": "",
    "navi": "",
    "node": "",
    "nyancat": "",
    "openssl@1.1": "",
    "tree": "",
    "pass": "",
    "pastel": "",
    "perl": "",
    "pyenv": "",
    "python@3.10": "",
    "ruby": "",
    "rust": "",
    "spotify-tui": "",
    "telnet": "",
    "tmux": "",
    "vhs": "",
    "vim": "",
    "yarn": "",
    "acarl005/formulas/ls-go": "",
    "getsentry/tools/sentry-cli": "",
    "jandedobbeleer/oh-my-posh/oh-my-posh": "",
    "bierner.markdown-emoji": "",
    "dbaeumer.vscode-eslint": "",
    "esbenp.prettier-vscode": "",
    "haack.warp-companion": "",
    "ms-python.debugpy": "",
    "ms-python.isort": "",
    "ms-python.python": "",
    "ms-python.vscode-pylance": "",
    "ms-toolsai.jupyter": "",
    "ms-toolsai.jupyter-renderers": "",
    "ms-toolsai.vscode-jupyter-cell-tags": "",
    "ms-toolsai.vscode-jupyter-slideshow": ""
  };
  