export interface BrewfileLinkDictionary {
  [key: string]: string;
}

export const brewfileLinkDictionary: BrewfileLinkDictionary = {
  "acarl005/formulas": "https://github.com/acarl005/ls-go",
  "getsentry/tools": "https://github.com/getsentry/sentry",
  "homebrew/bundle": "https://github.com/Homebrew/homebrew-bundle",
  "homebrew/cask-fonts": "https://github.com/Homebrew/homebrew-cask-fonts",
  "homebrew/services": "https://github.com/Homebrew/homebrew-services",
  "python@3.11": "https://www.python.org/downloads/release/python-3110/",
  "asciinema": "https://github.com/asciinema/asciinema",
  "autojump": "https://github.com/wting/autojump",
  "berkeley-db": "https://github.com/berkeleydb/libdb",
  "carthage": "https://github.com/Carthage/Carthage",
  "clang-format":
    "https://github.com/llvm-mirror/clang/tree/master/tools/clang-format",
  "create-dmg": "https://github.com/create-dmg/create-dmg",
  "dbus": "https://github.com/godbus/dbus",
  "ffmpeg": "https://ffmpeg.org/",
  "exa": "https://the.exa.website/",
  "fzf": "https://github.com/junegunn/fzf",
  "gh": "https://github.com/cli/cli",
  "jq": "https://jqlang.github.io/jq/",
  "ruby": "https://www.ruby-lang.org/en/documentation/installation/",
  "node": "https://nodejs.org",
  "libtensorflow": "https://formulae.brew.sh/formula/libtensorflow",
  "libssh2": "https://libssh2.org/",
  "ddgr": "https://github.com/jarun/ddgr",
  "lolcat": "https://github.com/busyloop/lolcat",
  "diff-so-fancy": "https://github.com/so-fancy/diff-so-fancy",
  "figlet": "https://www.npmjs.com/package/figlet",
  "nyancat": "https://github.com/klange/nyancat",
  "jandedobbeleer/oh-my-posh/oh-my-posh": "https://ohmyposh.dev/",
  "tmux": "https://github.com/tmux/tmux/wiki",
  "spotify-tui": "https://github.com/Rigellute/spotify-tui",
  "pastel": "https://github.com/sharkdp/pastel",
  "openssl@1.1": "https://www.openssl.org/source/",
  "kubernetes-cli": "https://kubernetes.io/docs/tasks/tools/",
  "vhs": "https://github.com/charmbracelet/vhs",
  "acarl005/formulas/ls-go": "https://github.com/acarl005/ls-go",
  "getsentry/tools/sentry-cli": "https://github.com/getsentry/sentry-cli",
  "bierner.markdown-emoji": "https://github.com/mjbvz/vscode-markdown-emoji",
  "fish": "https://fishshell.com/",
  "perl": "https://www.perl.org/",
  "dbaeumer.vscode-eslint":
    "https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint",
  "eza": "https://eza.rocks/",
  "esbenp.prettier-vscode":
    "https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode",
  "haack.warp-companion":
    "https://marketplace.visualstudio.com/items?itemName=haack.warp-companion",
  "ms-python.debugpy":
    "https://marketplace.visualstudio.com/items?itemName=ms-python.debugpy",
  "ms-python.isort":
    "https://marketplace.visualstudio.com/items?itemName=ms-python.isort",
  "ms-python.python":
    "https://marketplace.visualstudio.com/items?itemName=ms-python.python",
  "ms-python.vscode-pylance":
    "https://marketplace.visualstudio.com/items?itemName=ms-python.vscode-pylance",
  "ms-toolsai.jupyter":
    "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter",
  "ms-toolsai.jupyter-renderers":
    "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.jupyter-renderers",
  "ms-toolsai.vscode-jupyter-cell-tags":
    "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-cell-tags",
  "ms-toolsai.vscode-jupyter-slideshow":
    "https://marketplace.visualstudio.com/items?itemName=ms-toolsai.vscode-jupyter-slideshow",
  "python@3.10": "https://www.python.org/downloads/release/python-3100/",
  "rust": "https://www.rust-lang.org/tools/install",
  "yarn": "https://yarnpkg.com/",
  "vim": "https://www.vim.org/",
  "unbound": "https://nlnetlabs.nl/projects/unbound/about/",
  "multitime": "https://formulae.brew.sh/formula/multitime",
  "gnutls": "https://formulae.brew.sh/formula/gnutls",
  "cmake": "https://formulae.brew.sh/formula/cmake",
  "bat": "https://github.com/sharkdp/bat",
  "withgraphite/tap": "https://github.com/withgraphite/homebrew-tap",
  "go": "https://formulae.brew.sh/formula/go",
  "krb5": "https://formulae.brew.sh/formula/krb5",
  "neofetch": "https://formulae.brew.sh/formula/neofetch",
  "pass": "https://formulae.brew.sh/formula/pass",
  "pnpm": "https://formulae.brew.sh/formula/pnpm",
  "pyenv-virtualenv": "https://formulae.brew.sh/formula/pyenv-virtualenv",
  "python@3.9": "https://formulae.brew.sh/formula/python@3.9",
  "starship":"https://formulae.brew.sh/formula/starship",
  "trunk":"https://formulae.brew.sh/formula/trunk",
  "withgraphite/tap/graphite":"https://github.com/withgraphite/homebrew-tap",
  "ms-azuretools.vscode-docker":"https://marketplace.visualstudio.com/items?itemName=ms-azuretools.vscode-docker",
  "ms-vscode-remote.remote-containers":"https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-containers",
  "withfig.fig":"https://formulae.brew.sh/cask/fig",
  "youtube-dl":"https://formulae.brew.sh/formula/youtube-dl",
  "warp":"https://www.warp.dev/",
  "python@3.12":"https://formulae.brew.sh/formula/python@3.12",
  "browsh-org/browsh":"https://www.brow.sh/docs/installation/",
  "heroku/brew":"https://github.com/heroku/homebrew-brew",
  "hidetatz/tap":"https://github.com/hidetatz/homebrew-tap",
  "hudochenkov/sshpass":"https://github.com/hudochenkov/homebrew-sshpass",
  "jotaen/klog":"https://github.com/jotaen/homebrew-klog",
  "keith/formulae":"https://github.com/keith/homebrew-formulae",
  "mongodb/brew":"https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/",
  "ngrok/ngrok":"https://formulae.brew.sh/cask/ngrok",
  "powershell/tap":"https://formulae.brew.sh/cask/powershell",
  "romkatv/powerlevel10k":"https://formulae.brew.sh/formula/powerlevel10k",
  "asdf":"https://formulae.brew.sh/formula/asdf",
  "bash":"https://formulae.brew.sh/formula/bash",
  "libgit2":"https://formulae.brew.sh/formula/libgit2",
  "freetype":"https://formulae.brew.sh/formula/freetype",
  "fontconfig":"https://formulae.brew.sh/formula/fontconfig",
  "little-cms2":"https://formulae.brew.sh/formula/little-cms2",
  "openjdk@11":"https://formulae.brew.sh/formula/openjdk@11",
  "bazel":"https://formulae.brew.sh/formula/bazel",
  "ccat":"https://formulae.brew.sh/formula/ccat",
  "chezmoi":"https://formulae.brew.sh/formula/chezmoi",
  "openjdk":"https://formulae.brew.sh/formula/openjdk",
  "clojure":"https://formulae.brew.sh/formula/clojure",
  "cocoapods":"https://formulae.brew.sh/formula/cocoapods",
  "cowsay":"https://formulae.brew.sh/formula/cowsay",
  "openldap":"https://formulae.brew.sh/formula/openldap",
  "rtmpdump":"https://formulae.brew.sh/formula/rtmpdump",
  "curl":"https://formulae.brew.sh/formula/curl",
  "direnv":"https://formulae.brew.sh/formula/direnv",
  "docker":"https://formulae.brew.sh/formula/docker",
  "docker,":"https://formulae.brew.sh/formula/docker",
  "emacs":"https://formulae.brew.sh/formula/emacs",
  "fastfetch":"https://formulae.brew.sh/formula/fastfetch",
  "gcc":"https://formulae.brew.sh/formula/gcc",
  "ghostscript":"https://formulae.brew.sh/formula/ghostscript",
  "git":"https://formulae.brew.sh/formula/git",
  "gnupg":"https://formulae.brew.sh/formula/gnupg",
  "gping":"https://formulae.brew.sh/formula/gping",
  "openjdk@17":"https://formulae.brew.sh/formula/openjdk@17",
  "gradle@7":"https://formulae.brew.sh/formula/gradle@7",
  "htop":"https://formulae.brew.sh/formula/htop",
  "iniparser":"https://formulae.brew.sh/formula/iniparser",
  "ipython":"https://formulae.brew.sh/formula/ipython",
  "istioctl":"https://formulae.brew.sh/formula/istioctl",
  "jenv":"https://formulae.brew.sh/formula/jenv",
  "jless":"https://formulae.brew.sh/formula/jless",
  "jp2a":"https://formulae.brew.sh/formula/jp2a",
  "jsonschema":"https://formulae.brew.sh/formula/jsonschema",
  "julia":"https://formulae.brew.sh/cask/julia",
  "just":"https://formulae.brew.sh/formula/just",
  "k9s":"https://formulae.brew.sh/formula/k9s",
  "keyring":"https://formulae.brew.sh/formula/keyring",
  "ksh93":"https://formulae.brew.sh/formula/ksh93",
  "kube-ps1":"https://formulae.brew.sh/formula/kube-ps1",
  "lazydocker":"https://github.com/jesseduffield/lazydocker",
  "lazygit":"https://github.com/jesseduffield/lazygit",
  "ldns":"https://formulae.brew.sh/formula/ldns",
  "lerna":"https://formulae.brew.sh/formula/lerna",
  "libfido2":"https://formulae.brew.sh/formula/libfido2",
  "libpq":"https://formulae.brew.sh/formula/libpq",
  "qemu":"https://formulae.brew.sh/formula/qemu",
  "lima":"https://formulae.brew.sh/formula/lima",
  "llvm":"https://formulae.brew.sh/formula/llvm",
  "llvm@16":"https://formulae.brew.sh/formula/llvm@16",
  "luv":"https://formulae.brew.sh/formula/luv",
  "maven":"https://formulae.brew.sh/formula/maven",
  "mesa":"https://formulae.brew.sh/formula/mesa",
  "micro":"https://formulae.brew.sh/formula/micro",
  "midnight-commander":"https://formulae.brew.sh/formula/midnight-commander",
  "minikube":"https://formulae.brew.sh/formula/minikube",
  "ncdu":"https://formulae.brew.sh/formula/ncdu",
  "ncspot":"https://formulae.brew.sh/formula/ncspot",
  "neovim":"https://formulae.brew.sh/formula/neovim",
  "neovide":"https://formulae.brew.sh/cask/neovide",
  "numpy":"https://formulae.brew.sh/formula/numpy",
  "nest":"https://formulae.brew.sh/formula/nest",
  "nnn":"https://formulae.brew.sh/formula/nnn",
  "node@16":"https://formulae.brew.sh/formula/node@16",
  "nushell":"https://formulae.brew.sh/formula/nushell",
  "oh-my-posh":"https://formulae.brew.sh/formula/oh-my-posh",
  "sqlparse":"https://formulae.brew.sh/formula/sqlparse",
  "pgcli":"https://formulae.brew.sh/formula/pgcli",
  "virtualenv":"https://formulae.brew.sh/formula/virtualenv",
  "pipenv":"https://formulae.brew.sh/formula/pipenv",
  "poetry":"https://formulae.brew.sh/formula/poetry",
  "ponysay":"https://formulae.brew.sh/formula/ponysay",
  "pre-commit":"https://formulae.brew.sh/formula/pre-commit",
  "tcl-tk":"https://formulae.brew.sh/formula/tcl-tk",
  "python@3.8":"https://formulae.brew.sh/formula/python@3.8",
  "webp":"https://formulae.brew.sh/formula/webp",
  "qt":"https://formulae.brew.sh/formula/qt",
  "ruby-build":"https://formulae.brew.sh/formula/ruby-build",
  "rbenv":"https://formulae.brew.sh/formula/rbenv",
  "ripgrep":"https://formulae.brew.sh/formula/ripgrep",
  "rpm":"https://formulae.brew.sh/formula/rpm",
  "screen":"https://formulae.brew.sh/formula/screen",
  "spaceship":"https://formulae.brew.sh/formula/spaceship",
  "terminal-notifier":"https://formulae.brew.sh/formula/terminal-notifier",
  "thefuck":"https://github.com/nvbn/thefuck",
  "typescript":"https://formulae.brew.sh/formula/typescript",
  "viu":"https://formulae.brew.sh/formula/viu",
  "vue-cli":"https://formulae.brew.sh/formula/vue-cli",
  "watch":"https://formulae.brew.sh/formula/watch",
  "wget":"https://formulae.brew.sh/formula/wget",
  "yadm":"https://formulae.brew.sh/formula/yadm",
  "zellij":"https://formulae.brew.sh/formula/zellij",
  "zsh":"https://formulae.brew.sh/formula/zsh",
  "zsh-vi-mode":"https://formulae.brew.sh/formula/zsh-vi-mode",
  "browsh-org/browsh/browsh":"https://www.brow.sh/docs/installation/",
  "hudochenkov/sshpass/sshpass":"https://github.com/hudochenkov/homebrew-sshpass",
  "mongodb/brew/mongodb-community-shell":"https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-os-x/",
  "powershell/tap/powershell":"https://formulae.brew.sh/cask/powershell",
  "github.vscode-pull-request-github":"https://github.com/microsoft/vscode-pull-request-github",
  "tamasfe.even-better-toml":"https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml",
  "1password/tap":"https://github.com/1Password/homebrew-tap",
  "codecrafters-io/tap":"https://github.com/codecrafters-io/homebrew-tap",
  "shopify/shopify":"https://shopify.dev/docs/api/shopify-cli",
  "supabase/tap":"https://github.com/supabase/homebrew-tap",
  "jpeg-xl":"https://formulae.brew.sh/formula/jpeg-xl",
  "aom":"https://formulae.brew.sh/formula/aom",
  "awscli":"https://formulae.brew.sh/formula/awscli",
  "glib":"https://formulae.brew.sh/formula/glib",
  "cmatrix":"https://formulae.brew.sh/formula/cmatrix",
  "deno":"https://formulae.brew.sh/formula/deno",
  "duti":"https://formulae.brew.sh/formula/duti",
  "p11-kit":"https://formulae.brew.sh/formula/p11-kit",
  "harfbuzz":"https://formulae.brew.sh/formula/harfbuzz",
  "libarchive":"https://formulae.brew.sh/formula/libarchive",
  "libass":"https://formulae.brew.sh/formula/libass",
  "srt":"https://formulae.brew.sh/formula/srt",
  "tesseract":"https://formulae.brew.sh/formula/tesseract",
  "gifsicle":"https://formulae.brew.sh/formula/gifsicle",
  "gobject-introspection":"https://formulae.brew.sh/formula/gobject-introspection",
  "guile":"https://formulae.brew.sh/formula/guile",
  "httpie":"https://formulae.brew.sh/formula/httpie",
  "hugo":"https://formulae.brew.sh/formula/hugo",
  "python-yq":"https://formulae.brew.sh/formula/python-yq",
  "tag":"https://formulae.brew.sh/formula/tag",
  "taskell":"https://formulae.brew.sh/formula/taskell",
};
